name: Release

on:
  release:
    types: [published]

jobs:
  validate-release:
    runs-on: ubuntu-latest
    name: Validate release
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

      - name: Validate version
        run: |
          version=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          manifest_version=$(grep '"version"' custom_components/snmp_printer/manifest.json | sed 's/.*"version": *"\([^"]*\)".*/\1/')
          
          if [ "$version" != "$manifest_version" ]; then
            echo "Version mismatch: Release $version != Manifest $manifest_version"
            exit 1
          fi
          
          echo "Version validation passed: $version"